name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Login Docker
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_TOKEN}}
      
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME}}/authorization_service:v0

      - name: Tag docker image
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/authorization_service:v0 ${{ secrets.DOCKERHUB_USERNAME }}/authorization_service:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME}}/authorization_service:v0
          docker push ${{ secrets.DOCKERHUB_USERNAME}}/authorization_service:latest
